export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BUGER_SUCCESS = 'PURCHASE_BUGER_SUCCESS';
export const PURCHASE_BUGER_FAILED = 'PURCHASE_BUGER_FAILED';
export const PURCHASE_BUGER_START = 'PURCHASE_BUGER_START';